### ISSUE TITLE
Train.py Execution Error Questions

### ISSUE THREAD

**Issue by CHK-0000** [CODEJIN/NaturalSpeech2#10]
python Train.py -hp C:\NaturalSpeech2\Hyper_Parameters.yaml -s 4
Running with the following command will result in an error
___
Traceback (most recent call last):
  File "c:\NaturalSpeech2\Train.py", line 717, in <module>
    trainer = Trainer(hp_path= args.hyper_parameters, steps= args.steps)
  File "c:\NaturalSpeech2\Train.py", line 60, in __init__
    self.Dataset_Generate()
  File "c:\NaturalSpeech2\Train.py", line 88, in Dataset_Generate
    self.latent_min = min([x['Min'] for x in latent_info_dict.values()])
ValueError: min() arg is an empty sequence

**Comment by CODEJIN** [comment]
Hello. According to the error message you wrote, it appears that the dataset was not created properly. Were there any problems when creating the dataset with the pattern generator? Check if 'Latent_Info.yaml' is in the path of 'Latent_Info_Path' in 'Hyper_Parameters.yaml', and check how many speakers there are. If there is no one, there appears to have been a problem while creating the dataset.
