### ISSUE TITLE
Training result

### ISSUE THREAD

**Issue by FlyToYourMooN** [CODEJIN/NaturalSpeech2#3]
Hi, thank you very much for your exciting work! Can the model currently produce understandable audio？

**Comment by CODEJIN** [comment]
Dear @FlyToYourMooN 

I am currently testing the training feasibility, and this audio is the result of training with a single speaker (LJSpeech), batch size 8, and 409K iterations: [Evaluation.Audio.Linear_409000_4945295b61b1b2cf476c.zip](https://github.com/CODEJIN/NaturalSpeech2/files/11521216/Evaluation.Audio.Linear_409000_4945295b61b1b2cf476c.zip)

The diffusion loss is still decreasing, but considering that even with a single speaker, stable performance is not achieved. So, I think there is a need for improvement in the architecture or loss terms. If you have any suggestions for improvement methods, please let me know!

Best regards,

Heejo
