### ISSUE TITLE
Can you provide the checkpoint?

### ISSUE THREAD

**Issue by yingfenging** [CODEJIN/NaturalSpeech2#6]
hello, can you provide the LJ checkpoint  in  Inference.ipynb, and the name is "./results/LJ_230518/Checkpoint/S_45000.pt"

Thank you.

**Comment by CODEJIN** [comment]
Dear @yingfenging ,

Hello. I'm sorry, but the mentioned version was trained a long time ago, and the model's structure has undergone significant changes. Therefore, it may not be properly applicable to the current model. After making some additional modifications, I will share a version that has been trained briefly.

Best regards,

Heejo
