### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by ethanyhzhang** [CODEJIN/NaturalSpeech2#7]
Hi @CODEJIN,
    Thanks for your nice work, and it seems something meaningful after training could be produced. 
    But it borders me on how to run the code. As there are so many Hyper path needed to be set. Are they all needed? For example, if I have downloaed LJ Speech dataset, how could I run the code based on it? Could you please tell us more details about running the code? 
    Thanks for your kindness again! ^_^

**Comment by CODEJIN** [comment]
Dear @ethanyhzhang ,

Hello, thanks for your interest in the repository!

To proceed with training using LJSpeech dataset, you'll need to follow these steps:

1. Set the dataset path in Hyper_Parameters.yaml.
* The current repository's Hyper_Parameters.yaml has it set to 'F:/Datasets/22K.NaturalSpeech2.VCTK,' but you should change these paths to your desired location.
* 
2. Configure preprocessing patterns using the pattern generator.
````
python Pattern_Generate.py -lj <LJSpeech dataset path>
````

3. Execute the training.
````
python Train.py -hp Hyper_Parameters.yaml
````

I'm sorry if the preprocessing adds an extra complexity. However, it's designed to enhance training speed and data management. Your understanding is appreciated. If there are issues with Phonemizer, you can refer to [here](https://github.com/CODEJIN/NaturalSpeech2#about-phonemizer).

Thanks.

**Comment by ethanyhzhang** [comment]
Many thanks for your reply @CODEJIN ! I had thought there would be no response for the issue. what a suprise! 

I'll try it again, hope it works.

**Comment by ethanyhzhang** [comment]
> Dear @ethanyhzhang ,
> 
> Hello, thanks for your interest in the repository!
> 
> To proceed with training using LJSpeech dataset, you'll need to follow these steps:
> 
> 1. Set the dataset path in Hyper_Parameters.yaml.
> 
> * The current repository's Hyper_Parameters.yaml has it set to 'F:/Datasets/22K.NaturalSpeech2.VCTK,' but you should change these paths to your desired location.
> 
> 2. Configure preprocessing patterns using the pattern generator.
> 
> ```
> python Pattern_Generate.py -lj <LJSpeech dataset path>
> ```
> 
> 3. Execute the training.
> 
> ```
> python Train.py -hp Hyper_Parameters.yaml
> ```
> 
> I'm sorry if the preprocessing adds an extra complexity. However, it's designed to enhance training speed and data management. Your understanding is appreciated. If there are issues with Phonemizer, you can refer to [here](https://github.com/CODEJIN/NaturalSpeech2#about-phonemizer).
> 
> Thanks.

It works. Thanks again and I'll close this issue.
